package jviewer.controller.orbHistory.HistoryExtendedPackage;


/**
* jviewer/controller/orbHistory/HistoryExtendedPackage/ClientInfoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ControllerHistory.idl
* Sunday, November 18, 2012 7:59:07 PM MSK
*/

public final class ClientInfoHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public ClientInfoHolder ()
  {
  }

  public ClientInfoHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = jviewer.controller.orbHistory.HistoryExtendedPackage.ClientInfoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    jviewer.controller.orbHistory.HistoryExtendedPackage.ClientInfoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return jviewer.controller.orbHistory.HistoryExtendedPackage.ClientInfoHelper.type ();
  }

}
