package jviewer.controller.orbHistory;

/**
* jviewer/controller/orbHistory/HistoryExtendedHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ControllerHistory.idl
* Sunday, November 18, 2012 7:59:07 PM MSK
*/

public final class HistoryExtendedHolder implements org.omg.CORBA.portable.Streamable
{
  public jviewer.controller.orbHistory.HistoryExtended value = null;

  public HistoryExtendedHolder ()
  {
  }

  public HistoryExtendedHolder (jviewer.controller.orbHistory.HistoryExtended initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = jviewer.controller.orbHistory.HistoryExtendedHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    jviewer.controller.orbHistory.HistoryExtendedHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return jviewer.controller.orbHistory.HistoryExtendedHelper.type ();
  }

}
