package jviewer.controller.orbHistory;


/**
* jviewer/controller/orbHistory/HistoryHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ControllerHistory.idl
* Sunday, November 18, 2012 7:59:07 PM MSK
*/

abstract public class HistoryHelper
{
  private static String  _id = "IDL:jviewer/controller/orbHistory/History:1.0";

  public static void insert (org.omg.CORBA.Any a, jviewer.controller.orbHistory.History that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static jviewer.controller.orbHistory.History extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (jviewer.controller.orbHistory.HistoryHelper.id (), "History");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static jviewer.controller.orbHistory.History read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_HistoryStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, jviewer.controller.orbHistory.History value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static jviewer.controller.orbHistory.History narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof jviewer.controller.orbHistory.History)
      return (jviewer.controller.orbHistory.History)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      jviewer.controller.orbHistory._HistoryStub stub = new jviewer.controller.orbHistory._HistoryStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static jviewer.controller.orbHistory.History unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof jviewer.controller.orbHistory.History)
      return (jviewer.controller.orbHistory.History)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      jviewer.controller.orbHistory._HistoryStub stub = new jviewer.controller.orbHistory._HistoryStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
