package jviewer.controller.orbHistory;


/**
* jviewer/controller/orbHistory/HistoryOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ControllerHistory.idl
* Sunday, November 18, 2012 7:59:07 PM MSK
*/

public interface HistoryOperations 
{
  String[] getHistory (int clientId);
  boolean login (String login, String password);
  boolean logout (int clientId);
} // interface HistoryOperations
