package jviewer.controller.orbHistory;


/**
* jviewer/controller/orbHistory/HistoryPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ControllerHistory.idl
* Sunday, November 18, 2012 7:59:07 PM MSK
*/

public abstract class HistoryPOA extends org.omg.PortableServer.Servant
 implements jviewer.controller.orbHistory.HistoryOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getHistory", new java.lang.Integer (0));
    _methods.put ("login", new java.lang.Integer (1));
    _methods.put ("logout", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // jviewer/controller/orbHistory/History/getHistory
       {
         int clientId = in.read_long ();
         String $result[] = null;
         $result = this.getHistory (clientId);
         out = $rh.createReply();
         jviewer.controller.orbHistory.HistoryPackage.historyHelper.write (out, $result);
         break;
       }

       case 1:  // jviewer/controller/orbHistory/History/login
       {
         String login = in.read_string ();
         String password = in.read_string ();
         boolean $result = false;
         $result = this.login (login, password);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // jviewer/controller/orbHistory/History/logout
       {
         int clientId = in.read_long ();
         boolean $result = false;
         $result = this.logout (clientId);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:jviewer/controller/orbHistory/History:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public History _this() 
  {
    return HistoryHelper.narrow(
    super._this_object());
  }

  public History _this(org.omg.CORBA.ORB orb) 
  {
    return HistoryHelper.narrow(
    super._this_object(orb));
  }


} // class HistoryPOA
