package jviewer.controller.orbHistory;

/**
* jviewer/controller/orbHistory/HistoryHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ControllerHistory.idl
* Sunday, November 18, 2012 7:59:07 PM MSK
*/

public final class HistoryHolder implements org.omg.CORBA.portable.Streamable
{
  public jviewer.controller.orbHistory.History value = null;

  public HistoryHolder ()
  {
  }

  public HistoryHolder (jviewer.controller.orbHistory.History initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = jviewer.controller.orbHistory.HistoryHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    jviewer.controller.orbHistory.HistoryHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return jviewer.controller.orbHistory.HistoryHelper.type ();
  }

}
