package jviewer.controller.orbHistory;


/**
* jviewer/controller/orbHistory/History.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ControllerHistory.idl
* Sunday, November 18, 2012 7:59:07 PM MSK
*/

public interface History extends HistoryOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface History
