package jviewer.controller.orbHistory;


/**
* jviewer/controller/orbHistory/HistoryExtended.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ControllerHistory.idl
* Sunday, November 18, 2012 7:59:07 PM MSK
*/

public interface HistoryExtended extends HistoryExtendedOperations, jviewer.controller.orbHistory.History, org.omg.CORBA.portable.IDLEntity 
{
} // interface HistoryExtended
